trainingInput:
  hyperparameters:
    goal: MAXIMIZE
    hyperparameterMetricTag: accuracy
    maxTrials: 4
    maxParallelTrials: 1
    params:
      - parameterName: first-layer-size
        type: INTEGER
        minValue: 4
        maxValue: 16
        scaleType: UNIT_LINEAR_SCALE
      - parameterName: num-layers
        type: INTEGER
        minValue: 1
        maxValue: 4
        scaleType: UNIT_LINEAR_SCALE
      - parameterName: scale-factor
        type: DOUBLE
        minValue: 0.7
        maxValue: 1.0
        scaleType: UNIT_REVERSE_LOG_SCALE
      # Add tuning for embedding size, see suggestion for solution below










      # A solution:
      # - parameterName: embedding-size
      #   type: INTEGER
      #   minValue: 2
      #   maxValue: 4
      #   scaleType: UNIT_LINEAR_SCALE
